ci: WIP

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -10,12 +10,17 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4.1.7
-    - name: Setup .NET Core
-      uses: actions/setup-dotnet@v4.0.0
-      with:
-        dotnet-version: 8.0.100
-    - name: Build
-      run: dotnet build --configuration Release
-    - name: Test
-      run: dotnet test --configuration Release --no-restore --no-build
+      - uses: actions/checkout@v4.1.7
+      - name: Setup .NET Core
+        uses: actions/setup-dotnet@v4.0.0
+        with:
+          dotnet-version: 8.0.100
+      - run: dotnet build --configuration Release
+      - run: |
+          dotnet test --configuration Release --no-restore --no-build \
+                      --logger "trx;LogFileName=$(PWD)/logs/test-results.trx"
+      - uses: actions/upload-artifact@v4  # upload test results
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: test-results
+          path: $(PWD)/logs/test-results.trx
